[package]
name = "nnue"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"], optional = true }
pleco = { path = "../pleco" }
binread = { version = "2", features = ["const_generics"] }

[features]
default = ["serde"]
serde = ["dep:serde"]
